with open("fpv_tuner/ui/pages/export_page.py", "r") as f:
    code = f.read()

import re

target = """    def _copy_to_clipboard(self):
        self._copy_text_to_clipboard(self._cli_text)
        self.copy_btn.setText("✅  Copied!")
        from PyQt6.QtCore import QTimer
        QTimer.singleShot(2000, lambda: self.copy_btn.setText("📋  Copy to Clipboard"))"""

replacement = target + """

    def _save_to_preset(self):
        from PyQt6.QtWidgets import QFileDialog
        path, _ = QFileDialog.getSaveFileName(self, "Save Betaflight Preset", "", "Text Files (*.txt);;All Files (*)")
        if not path:
            return
            
        header = (
            "# Betaflight Preset\\n"
            "# Generated by Open Tuning Tool\\n"
            "# category: TUNING\\n"
            "# status: OFFICIAL\\n"
            "\\n"
        )
        
        try:
            with open(path, "w") as f:
                f.write(header + self._cli_text)
        except Exception as e:
            print(f"Failed to save: {e}")"""

code = code.replace(target, replacement)
with open("fpv_tuner/ui/pages/export_page.py", "w") as f:
    f.write(code)
