with open("fpv_tuner/ui/pages/export_page.py", "r") as f:
    code = f.read()

import re

target_btns = """        self.copy_btn = QPushButton("📋  Copy to Clipboard")
        self.copy_btn.setProperty("variant", "ghost")
        self.copy_btn.clicked.connect(self._copy_to_clipboard)
        btn_layout.addWidget(self.copy_btn)

        btn_layout.addStretch()"""

replacement_btns = """        self.copy_btn = QPushButton("📋  Copy to Clipboard")
        self.copy_btn.setProperty("variant", "ghost")
        self.copy_btn.clicked.connect(self._copy_to_clipboard)
        btn_layout.addWidget(self.copy_btn)

        self.save_btn = QPushButton("💾  Save as Preset")
        self.save_btn.setProperty("variant", "ghost")
        self.save_btn.clicked.connect(self._save_to_preset)
        btn_layout.addWidget(self.save_btn)

        btn_layout.addStretch()"""

code = code.replace(target_btns, replacement_btns)

target_copy = """    def _copy_to_clipboard(self):
        from PyQt6.QtWidgets import QApplication
        QApplication.clipboard().setText(self._cli_text)
        self.toasts.success("Copied to clipboard!")"""

replacement_copy = """    def _copy_to_clipboard(self):
        from PyQt6.QtWidgets import QApplication
        QApplication.clipboard().setText(self._cli_text)
        self.toasts.success("Copied to clipboard!")

    def _save_to_preset(self):
        from PyQt6.QtWidgets import QFileDialog
        path, _ = QFileDialog.getSaveFileName(self, "Save Betaflight Preset", "", "Text Files (*.txt);;All Files (*)")
        if not path:
            return
            
        header = (
            "# Betaflight Preset\\n"
            "# Generated by FPV Tuner\\n"
            "# category: TUNING\\n"
            "# status: OFFICIAL\\n"
            "\\n"
        )
        
        try:
            with open(path, "w") as f:
                f.write(header + self._cli_text)
            self.toasts.success(f"Preset saved to {path}")
        except Exception as e:
            self.toasts.error(f"Failed to save: {e}")"""

code = code.replace(target_copy, replacement_copy)

with open("fpv_tuner/ui/pages/export_page.py", "w") as f:
    f.write(code)
